# Generated by rust2rpm 27
%bcond check 1

%global crate viu

Name:           rust-viu
Version:        1.5.1
Release:        %autorelease
Summary:        View images right from the terminal

License:        MIT
URL:            https://crates.io/crates/viu
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
View images right from the terminal.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%{_bindir}/viu

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

# Test fails because of missing file that would need to be bundled...
%if %{with check}
%check
# cargo_test
%endif

%changelog
%autochangelog
