SPEC := "{{ cookiecutter.package }}.spec"

# Build the source rpm
srpm:
  spec="$(pwd)/{% raw %}{{ SPEC }}{% endraw %}" outdir="$(pwd)" topdir="$(pwd)/build" downloaddir="$(pwd)/downloads" make -f ../../.copr/Makefile srpm

# Verify the source rpm
verify:
  spec="$(pwd)/{% raw %}{{ SPEC }}{% endraw %}" outdir="$(pwd)" topdir="$(pwd)/build" downloaddir="$(pwd)/downloads" bash ../../scripts/verify-srpm.sh

lint:
  shellcheck ./srpm.sh

# Build and verify
test: clean srpm verify

# Clean files created from building and verifying
clean:
  rm -f '{% raw %}{{ SPEC }}{% endraw %}'
  rm -rf ./build
  rm -rf ./downloads
  rm -f *.src.rpm
  rm -f *.tar.gz

# Fail if there are uncommitted files
check-dirty:
  ./scripts/is-dirty.sh

# Apply copr configuration
apply:
  coprctl apply -f ./package.yml

build: check-dirty apply
  copr build-package '{{ cookiecutter.copr }}' --name "$(sed 's/\.spec//' <<< '{% raw %}{{SPEC}}{% endraw %}')"
