# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/hairyhenderson/gomplate
%global goipath         github.com/hairyhenderson/gomplate
Version:                4.3.2

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
A flexible commandline tool for template rendering. Supports lots of local and
remote datasources.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md CONTRIBUTING.md README.md docs-\\\
                        src/content/functions/func_doc.md.tmpl

Name:           golang-github-hairyhenderson-gomplate
Release:        %autorelease
Summary:        A flexible commandline tool for template rendering. Supports lots of local and remote datasources

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
BuildRequires:  golang-x-crypto-devel
BuildRequires:  golang(cuelang.org/go/cue)
BuildRequires:  golang(cuelang.org/go/cue/cuecontext)
BuildRequires:  golang(cuelang.org/go/cue/format)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/ec2)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/kms)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/sts)
BuildRequires:  golang(github.com/fullsailor/pkcs7)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/gosimple/slug)
BuildRequires:  golang(github.com/hack-pad/hackpadfs)
BuildRequires:  golang(github.com/hack-pad/hackpadfs/mem)
BuildRequires:  golang(github.com/hack-pad/hackpadfs/os)
BuildRequires:  golang(github.com/hairyhenderson/go-fsimpl)
BuildRequires:  golang(github.com/hairyhenderson/go-fsimpl/autofs)
BuildRequires:  golang(github.com/hairyhenderson/go-fsimpl/gitfs)
BuildRequires:  golang(github.com/hairyhenderson/go-fsimpl/httpfs)
BuildRequires:  golang(github.com/hairyhenderson/go-fsimpl/vaultfs/vaultauth)
BuildRequires:  golang(github.com/hairyhenderson/toml)
BuildRequires:  golang(github.com/hairyhenderson/xignore)
BuildRequires:  golang(github.com/hairyhenderson/yaml)
BuildRequires:  golang(github.com/hashicorp/go-sockaddr)
BuildRequires:  golang(github.com/hashicorp/go-sockaddr/template)
BuildRequires:  golang(github.com/hashicorp/vault/api)
BuildRequires:  golang(github.com/hashicorp/vault/api/auth/aws)
BuildRequires:  golang(github.com/itchyny/gojq)
BuildRequires:  golang(github.com/johannesboyne/gofakes3)
BuildRequires:  golang(github.com/johannesboyne/gofakes3/backend/s3mem)
BuildRequires:  golang(github.com/joho/godotenv)
BuildRequires:  golang(github.com/lmittmann/tint)
BuildRequires:  golang(github.com/Masterminds/goutils)
BuildRequires:  golang(github.com/Masterminds/semver/v3)
BuildRequires:  golang(github.com/Shopify/ejson)
BuildRequires:  golang(github.com/Shopify/ejson/json)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(github.com/ugorji/go/codec)
BuildRequires:  golang(go4.org/netipx)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/term)
BuildRequires:  golang(golang.org/x/text/cases)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(gotest.tools/v3/assert)
BuildRequires:  golang(gotest.tools/v3/assert/cmp)
BuildRequires:  golang(gotest.tools/v3/fs)
BuildRequires:  golang(gotest.tools/v3/icmd)
BuildRequires:  golang(inet.af/netaddr)
BuildRequires:  golang(k8s.io/client-go/util/jsonpath)
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in version/gen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs CHANGELOG.md CONTRIBUTING.md README.md
%doc docs-src/content/functions/func_doc.md.tmpl
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
