apiVersion: coprctl/v1alpha1
kind: package-scm
metadata:
  name: rust-yaml-rust2
spec:
  auto_rebuild: false
  ownername: jfhbrook
  projectname: joshiverse
  clone-url: https://github.com/jfhbrook/copr
  commit: null
  subdir: packages/rust-yaml-rust2
  spec: rust-yaml-rust2.spec
  type: git
  method: make_srpm
  enable_net: true
