# Generated by rust2rpm 27
%bcond check 1

%global crate starship

Name:           rust-starship
Version:        1.23.0
Release:        %autorelease
Summary:        Minimal, blazing-fast, and infinitely customizable prompt for any shell! ☄🌌️

License:        ISC
URL:            https://crates.io/crates/starship
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          starship-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The minimal, blazing-fast, and infinitely customizable prompt for any
shell! ☄🌌️.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/starship

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+battery-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+battery-devel %{_description}

This package contains library source intended for building other packages which
use the "battery" feature of the "%{crate}" crate.

%files       -n %{name}+battery-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+config-schema-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+config-schema-devel %{_description}

This package contains library source intended for building other packages which
use the "config-schema" feature of the "%{crate}" crate.

%files       -n %{name}+config-schema-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+notify-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+notify-devel %{_description}

This package contains library source intended for building other packages which
use the "notify" feature of the "%{crate}" crate.

%files       -n %{name}+notify-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+notify-rust-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+notify-rust-devel %{_description}

This package contains library source intended for building other packages which
use the "notify-rust" feature of the "%{crate}" crate.

%files       -n %{name}+notify-rust-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+schemars-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+schemars-devel %{_description}

This package contains library source intended for building other packages which
use the "schemars" feature of the "%{crate}" crate.

%files       -n %{name}+schemars-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+starship-battery-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+starship-battery-devel %{_description}

This package contains library source intended for building other packages which
use the "starship-battery" feature of the "%{crate}" crate.

%files       -n %{name}+starship-battery-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
