SPEC := "rust-versions.spec"

# Build the source rpm
srpm:
  ../../scripts/build-srpm.sh '{{ SPEC }}'

# Verify the source rpm
verify: srpm
  ../../scripts/verify-srpm.sh

lint:
  shellcheck ./srpm.sh

# Build and verify
test: clean srpm verify

# Clean files created from building and verifying
clean:
  ../../scripts/clean-srpm.sh '{{ SPEC }}'

# Fail if there are uncommitted files
check-dirty:
  ../../scripts/is-dirty.sh

push:
  git push origin main

# Apply copr configuration
apply:
  coprctl apply -f ./package.yml

build: check-dirty push apply
  ../../scripts/build-copr-spec.sh '{{ SPEC }}'
