# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate viuer

Name:           rust-viuer
Version:        0.9.1
Release:        %autorelease
Summary:        Display images in the terminal

License:        MIT
URL:            https://crates.io/crates/viuer
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
# Patch:          viuer-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Display images in the terminal.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+print-file-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+print-file-devel %{_description}

This package contains library source intended for building other packages which
use the "print-file" feature of the "%{crate}" crate.

%files       -n %{name}+print-file-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sixel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sixel-devel %{_description}

This package contains library source intended for building other packages which
use the "sixel" feature of the "%{crate}" crate.

%files       -n %{name}+sixel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sixel-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sixel-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "sixel-rs" feature of the "%{crate}" crate.

%files       -n %{name}+sixel-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
